.gitignore
src/components/form/timeout/TimeoutControl.tsx

Needed for the new flow editor. Now we need to point to this repository in package.json of RapidPro.

Added timeout for less than 1 minute

---

src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap
src/components/flow/actions/calllookup/CallLookup.tsx
src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.tsx.snap
src/components/form/timeout/__snapshots__/TimeoutControl.test.ts.snap
src/config/__snapshots__/typeConfigs.test.ts.snap
src/external/index.ts

- An issue where only 1 item was been displayed in the select
- Crash after saving lookup

Fix Lookup

---

lambda/lookups.js
src/components/flow/routers/lookup/Context.tsx
src/components/flow/routers/lookup/LookupParamaterField.tsx
src/components/flow/routers/lookup/LookupParametersForm.module.scss
src/components/flow/routers/lookup/LookupParametersForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/components/flow/routers/lookup/helpers.ts
src/components/form/select/SelectElement.tsx
src/flowTypes.ts

Lookup parameters

---

lambda/link.js
public/index.html
src/components/flow/actions/addurn/__snapshots__/AddURNForm.test.tsx.snap
src/components/flow/actions/shortenurl/ShortenUrl.tsx
src/components/flow/routers/giftcard/GiftCardRouterForm.tsx
src/components/flow/routers/giftcard/helpers.ts
src/components/flow/routers/helpers.ts
src/components/flow/routers/lookup/LookupParametersForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/components/flow/routers/lookup/helpers.ts
src/components/flow/routers/random/__snapshots__/RandomRouterForm.test.tsx.snap
src/components/flow/routers/shortenurl/ShortenUrlForm.tsx
src/components/flow/routers/shortenurl/helpers.tsx
src/components/shared.module.scss
src/config/__snapshots__/typeConfigs.test.ts.snap
src/config/interfaces.ts
src/config/typeConfigs.ts
src/external/index.ts
src/flowTypes.ts
src/store/flowContext.ts

- Added Trackable links UI Implementation

Trackable links

---

src/components/flow/routers/lookup/Context.tsx
src/components/flow/routers/lookup/LookupParamaterField.tsx
src/components/flow/routers/lookup/LookupParametersForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/components/flow/routers/lookup/helpers.ts
src/components/flow/routers/lookup/validators.tsx

- Validate lookup parameters
- Prevent saving lookup when it has a lookup parameter with error

Lookup parameters validation

---

src/components/form/timeout/TimeoutControl.tsx
src/components/form/timeout/__snapshots__/TimeoutControl.test.ts.snap

Added timeout of 30 mins in the new flow editor

---

src/components/flow/routers/lookup/LookupParamaterField.tsx
src/components/flow/routers/lookup/LookupParametersForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/config/interfaces.ts
src/config/typeConfigs.ts

- Prevent saving lookup form when the form is not valid
---
- https://app.asana.com/0/1151568128615717/1154018580653378
- https://app.asana.com/0/1151568128615717/1154101564853411

Do not save lookup when form is not valid

---

src/components/flow/routers/shortenurl/ShortenUrlForm.tsx
src/components/flow/routers/widgets.tsx

task: https://app.asana.com/0/1157657135078032/1154432875217252/f

Remove help text on Shorten Trackable Link modal

---

src/components/flow/routers/giftcard/GiftCardRouterForm.tsx
src/components/flow/routers/response/ResponseRouterForm.test.ts
src/components/flow/routers/response/ResponseRouterForm.tsx
src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
src/components/flow/routers/response/helpers.ts
src/components/helpicon/HelpIcon.module.scss
src/components/helpicon/HelpIcon.test.tsx
src/components/helpicon/HelpIcon.tsx
src/components/helpicon/__snapshots__/HelpIcon.test.tsx.snap
src/components/spellchecker/SpellChecker.module.scss
src/components/spellchecker/SpellChecker.test.ts
src/components/spellchecker/SpellChecker.tsx
src/components/spellchecker/__snapshots__/SpellChecker.test.ts.snap
src/flowTypes.ts
src/variables.module.scss

Task: https://app.asana.com/0/1157657135078032/1152481332340151/f

Add spell check for "Wait for Response"

---

src/components/button/Button.module.scss
src/components/shared.module.scss
src/palette_ec.scss

Task: https://app.asana.com/0/1152254835058569/1152550718426857/f

Change default colors for buttons and send msg flow step

---

src/config/interfaces.ts
src/config/operatorConfigs.ts

Task https://app.asana.com/0/1159876841343611/1152483606380670/f

Feature: Has an image rule

---

lambda/attachments.js
lambda/attachments_validation.js
public/index.html
src/components/__snapshots__/index.test.ts.snap
src/components/flow/actions/sendemail/SendEmailForm.module.scss
src/components/flow/actions/sendemail/SendEmailForm.tsx
src/components/flow/actions/sendemail/helpers.ts
src/components/form/select/tags/TaggingElement.tsx
src/flowTypes.ts
src/test/config.ts

Task: https://app.asana.com/0/1159876841343611/1158544836278234/f

Url attachments validation on email attachments page

---

src/components/flow/routers/giftcard/GiftCardRouterForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/components/flow/routers/resthook/ResthookRouterForm.tsx
src/components/flow/routers/shortenurl/ShortenUrlForm.tsx
src/components/flow/routers/webhook/WebhookRouterForm.tsx

Task: https://app.asana.com/0/1159876841343611/1152050780796883/f
I also did the same fixes in other places where I found the same issue.

Bugfix: Gift card issues.

---

src/components/flow/actions/sendemail/SendEmailForm.tsx

Task: https://app.asana.com/0/0/1174860717945777/f

Bug: Issues fixing for send email attachments

---

src/config/operatorConfigs.ts

Issue: https://app.asana.com/0/0/1178482176781915/f

Hide has an image rule from phone and serveyor flows

---

src/components/flow/routers/lookup/LookupParamaterField.tsx

Issue: https://app.asana.com/0/0/1174110665223489/f

Issue: Autocomplete for lookup params

---

src/components/flow/Flow.tsx
src/components/flow/routers/giftcard/GiftCardRouterForm.tsx
src/components/flow/routers/localization/RouterLocalizationForm.tsx
src/components/flow/routers/lookup/LookupRouterForm.tsx
src/components/sticky/Sticky.tsx

https://app.asana.com/0/1152254835058569/1172364547402579/f
Issue: https://app.asana.com/0/1152254835058569/1180263981209273/f
Issue: https://app.asana.com/0/1159876841343611/1154018580653382

Bug: Resolving QA Issues

---

src/components/flow/Flow.tsx

Issue: https://app.asana.com/0/1159876841343611/1181626376824059/f

Bug: Fixed flow step connection issue

---

src/components/flow/actions/sendmsg/SendMsgForm.tsx

Issue: https://app.asana.com/0/1152254835058569/1172381037876937/f

Bug: Fixing audio attachments validation on send message form.

---

src/components/flow/Flow.tsx
src/components/flow/routers/case/__snapshots__/helpers.test.ts.snap
src/components/flow/routers/response/ResponseRouterForm.tsx
src/components/flow/routers/response/helpers.ts
src/components/spellchecker/SpellChecker.module.scss
src/components/spellchecker/SpellChecker.test.ts
src/components/spellchecker/SpellChecker.tsx
src/components/spellchecker/__snapshots__/SpellChecker.test.ts.snap
src/config/i18n/defaults.json
src/flowTypes.ts

Task: https://app.asana.com/0/0/1181446417194561/f
+
Solved flow steps connection issue. 
Issue: https://app.asana.com/0/1159876841343611/1181626376824059/f

Feature: Spell checker

---

src/components/flow/routers/response/ResponseRouterForm.tsx

Issue: https://app.asana.com/0/0/1183082285204051/f

Bug: Filter for spell checker feature

---

src/components/spellchecker/SpellChecker.tsx

Issue: https://app.asana.com/0/1159876841343611/1164209761122917/f

Bug: Correction Sensitivity slide bar is wrong

---

src/components/dialog/Dialog.tsx
src/components/flow/routers/response/ResponseRouterForm.module.scss
src/components/flow/routers/response/ResponseRouterForm.tsx
src/components/flow/routers/response/helpers.ts
src/components/nodeeditor/NodeEditor.tsx
src/store/nodeEditor.ts

Issue: https://app.asana.com/0/0/1188633552021083/f
Issue: https://app.asana.com/0/0/1188633552021081/f
Issue: https://app.asana.com/0/0/1189011770861849/f
Bug: https://app.asana.com/0/0/1190611422293754/f

Bug: Regex testing

---

lambda/keyword_triggers.js
public/index.html
src/components/flow/routers/response/ResponseRouterForm.tsx
src/components/nodeeditor/NodeEditor.tsx
src/external/index.ts
src/flowTypes.ts
src/store/flowContext.ts
src/store/nodeEditor.ts
src/test/config.ts

Issue: https://app.asana.com/0/1159876841343611/1186094551686811/f
Related PR: https://github.com/greatnonprofits-nfp/rapidpro/pull/130

Issue: Using 'Wait for Response' input same as 'Trigger word' in a flow

---

src/components/flow/actions/helpers.tsx
src/flowTypes.ts

Issue: https://app.asana.com/0/1159876841343611/1185750108109221/f

Issue: Alert for mistyped trackable links

---

package.json
src/components/flow/routers/response/ResponseRouterForm.tsx

Issue: https://app.asana.com/0/1159876841343611/1186094551686811/f
Added translation

Issue: Keyword trigger in rules

---

src/components/flow/actions/helpers.tsx
src/components/flow/routers/response/helpers.ts

Issue: https://app.asana.com/0/0/1194359838843062/f (RegEx testing)
Issue: https://app.asana.com/0/1159876841343611/1193329833961289/f (Trackable Links Issues)

Bug: QA Issues

---

src/store/mutators.ts

Bug: https://app.asana.com/0/1152254835058569/1186875851198905/f

Bug: Deleting flow steps

---

src/components/flow/routers/response/ResponseRouterForm.tsx

Issue: https://app.asana.com/0/1159876841343611/1188633552021083/f

Bug: RegEx testing issues

---

src/components/flow/routers/response/ResponseRouterForm.tsx

Bug: https://app.asana.com/0/0/1196484810505738/f

Bug: Fixed partial match for the trigger words in response rules

---

src/components/simulator/Simulator.module.scss

Issue: https://app.asana.com/0/1152254835058569/1198910715362597/f

Bug: Set maximum height of quick reply block in simulator

---

src/components/contextmenu/ContextMenu.module.scss
src/components/contextmenu/ContextMenu.tsx
src/components/flow/Flow.tsx
src/components/flow/node/Node.tsx

Issue: https://app.asana.com/0/0/1199139172767617/f
Issue: https://app.asana.com/0/0/1199139499871207/f
Issue: https://app.asana.com/0/0/1199139172767614/f
Issue: https://app.asana.com/0/0/1199138906119888/f
Issue: https://app.asana.com/0/0/1199138906119885/f

Issues: Context menu

---

src/components/draghelper/DragHelper.tsx
src/components/flow/Flow.tsx

Issue: https://app.asana.com/0/0/1199153513640157/f
Issue: https://app.asana.com/0/0/1199162104017357/f
Issue: https://app.asana.com/0/0/1199139172767617/f
Issue: https://app.asana.com/0/0/1199153260000304/f

Bug: Context menu issues

---

src/components/flow/Flow.tsx
src/store/helpers.ts

Issue: https://app.asana.com/0/0/1199180312463904/f
+ Translations

Fixed bug with copying wait timeout flowsteps and fixed translations.

---

src/utils/index.tsx

Issue: https://app.asana.com/0/1152254835058569/1199170238270373/f

Bug: Not able to use "-" on Wait for Response results name

---

src/components/flow/Flow.tsx
src/store/mutators.ts
src/store/thunks.ts

Issue: https://app.asana.com/0/1159876841343611/1199247105599557/f

Bug: Cannot paste message

---

src/components/flow/actions/sendemail/SendEmailForm.module.scss
src/components/flow/actions/sendemail/SendEmailForm.tsx

Issue: https://app.asana.com/0/0/1199623520166950/f

Bug: Fixed issue with select on send email attachments tab

---

src/components/flow/routers/response/helpers.ts

Issue: https://app.asana.com/0/0/1199907716841271/f

Bug: Refactored logic for testing date fields in wait for response step.

---

src/config/typeConfigs.ts

Issue: https://app.asana.com/0/0/1199925230145670/f

Issue: 'Call Lookup' option displays in action/ruleset dropdown on new Surveyor flow editor

---

package.json
src/config/typeConfigs.ts

Ticket: https://app.asana.com/0/1159876841343611/1199934278365440/f

Removed "Shorten Trackable Links" option on 3.0

---

src/components/__snapshots__/index.test.ts.snap
src/components/flow/Flow.tsx
src/components/flow/actions/sendemail/__snapshots__/SendEmailForm.test.ts.snap
src/components/flow/actions/sendmsg/__snapshots__/SendMsgForm.test.ts.snap
src/components/flow/actions/startsession/__snapshots__/StartSessionForm.test.tsx.snap
src/components/flow/routers/response/__snapshots__/ResponseRouterForm.test.ts.snap
src/components/index.tsx
src/components/issues/__snapshots__/IssuesTab.test.tsx.snap
src/components/poptab/__snapshots__/PopTab.test.ts.snap
src/components/revisions/RevisionExplorer.tsx
src/components/simulator/__snapshots__/Simulator.test.ts.snap
src/components/translator/__snapshots__/TranslatorTab.test.tsx.snap
src/config/__snapshots__/typeConfigs.test.ts.snap

Issue: https://app.asana.com/0/0/1200099377983971/f
Issue: https://app.asana.com/0/0/1200099377983970/f
Issue: https://app.asana.com/0/0/1200095329124296/f

Bug: QA issues fixes for v3

---

src/components/simulator/LogEvent.tsx
src/store/helpers.ts

https://app.asana.com/0/1159876841343611/1200070609965959/f

Feature: Context menu with ability to copy message in simulator.

---

src/components/flow/actions/localization/MsgLocalizationForm.tsx
src/components/flow/actions/sendmsg/SendMsgForm.tsx
src/components/flow/actions/sendmsg/attachments.tsx

[Issue][FlowEditor] Receive attachment feature not included
https://app.asana.com/0/0/1200536543223149/f

Feature: Receive Attachment

---

src/components/flow/actions/sendmsg/SendMsgForm.tsx

Allow .vcard as file type for attachment/MMS
https://app.asana.com/0/1200626743215615/1200872637546825/f

Feature: Receive attachment feature

---

package.json
src/components/flow/actions/action/Action.module.scss
src/components/flow/actions/localization/MsgLocalizationForm.tsx
src/components/flow/actions/localization/__snapshots__/MsgLocalizationForm.test.ts.snap

https://app.asana.com/0/0/1201446538868292/f

Feature: Back Translation. Added translate button.

---

package.json
src/components/flow/actions/helpers.tsx
src/components/flow/actions/localization/MsgLocalizationForm.tsx

Back Translation to Confirm Accuracy of Translations Input
https://app.asana.com/0/1200626743215615/1201058156248705/f

Fixes: Back translation

---

package.json
src/components/nodeeditor/NodeEditor.tsx

Issue: When the "default" is different from "English".
https://app.asana.com/0/0/1201497048089202/f

Bugfix: Fixed issue with the default lang translation

---

src/components/flow/routers/response/ResponseRouterForm.tsx

https://app.asana.com/0/1200626743215615/1201527356339495/f

changed flow testing text
